// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDceuiYKaH6XAZlwZCT4yqnQEk-JdHpcBE',
    appId: '1:777809817811:web:134ab5e2c0203ab4ab6426',
    messagingSenderId: '777809817811',
    projectId: 'projeto-merenda',
    authDomain: 'projeto-merenda.firebaseapp.com',
    storageBucket: 'projeto-merenda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEGcC_E0UiaZJP-8aO5ZJIAlfEWcR_o0',
    appId: '1:777809817811:android:fead5a7bf5031595ab6426',
    messagingSenderId: '777809817811',
    projectId: 'projeto-merenda',
    storageBucket: 'projeto-merenda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMn3nsn1btiJwRtSLG1wX8JnuBryGIUA',
    appId: '1:777809817811:ios:8b85c9992565df80ab6426',
    messagingSenderId: '777809817811',
    projectId: 'projeto-merenda',
    storageBucket: 'projeto-merenda.firebasestorage.app',
    iosBundleId: 'com.example.projetoMerenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMn3nsn1btiJwRtSLG1wX8JnuBryGIUA',
    appId: '1:777809817811:ios:8b85c9992565df80ab6426',
    messagingSenderId: '777809817811',
    projectId: 'projeto-merenda',
    storageBucket: 'projeto-merenda.firebasestorage.app',
    iosBundleId: 'com.example.projetoMerenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDceuiYKaH6XAZlwZCT4yqnQEk-JdHpcBE',
    appId: '1:777809817811:web:d9b5a07c83262ce5ab6426',
    messagingSenderId: '777809817811',
    projectId: 'projeto-merenda',
    authDomain: 'projeto-merenda.firebaseapp.com',
    storageBucket: 'projeto-merenda.firebasestorage.app',
  );
}
